# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guidesign_10.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QTreeWidgetItem, QTreeWidget, QTreeView, QTableWidget, QTableWidgetItem, QSpinBox, QStatusBar, QDialog, QWidget, QPushButton, QLineEdit,
    QInputDialog, QApplication, QInputDialog, QLabel, QFrame)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 601)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../modbus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(self.centralwidget)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.treeWidget.setIndentation(15)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_2")
        self.btnWrite = QtWidgets.QPushButton(self.centralwidget)
        self.btnWrite.setObjectName("btnWrite")
        self.horizontalLayout_2.addWidget(self.btnWrite)
        self.btnUnits = QtWidgets.QPushButton(self.centralwidget)
        self.btnUnits.setObjectName("btnUnits")
        self.horizontalLayout_2.addWidget(self.btnUnits)
        self.checkDebug = QtWidgets.QCheckBox(self.centralwidget)
        self.checkDebug.setObjectName("checkDebug")
        self.horizontalLayout_2.addWidget(self.checkDebug)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBoxDataEncode = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxDataEncode.setObjectName("comboBoxDataEncode")
        self.comboBoxDataEncode.addItem("")
        self.comboBoxDataEncode.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxDataEncode)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBoxPollRate = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxPollRate.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxPollRate.setDecimals(3)
        self.spinBoxPollRate.setMinimum(0.1)
        self.spinBoxPollRate.setSingleStep(0.1)
        self.spinBoxPollRate.setProperty("value", 0.3)
        self.spinBoxPollRate.setObjectName("spinBoxPollRate")
        self.horizontalLayout_2.addWidget(self.spinBoxPollRate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)



        self.verticalLayout.addLayout(self.horizontalLayout_4)


        self.btnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdate.setObjectName("btnUpdate")
        self.horizontalLayout_4.addWidget(self.btnUpdate)

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")

        self.m_statusleft = QLabel("")
        self.m_statusleft.setFrameStyle(QFrame.Sunken)
        self.m_statusright = QLabel("TX:")
        self.m_statusright.setFrameStyle(QFrame.Panel)

        self.statusBar.addPermanentWidget(self.m_statusleft, 1)
        self.statusBar.addPermanentWidget(self.m_statusright, 2)

        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1239, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSetup = QtWidgets.QAction(MainWindow)
        self.actionSetup.setObjectName("actionSetup")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionSetup)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)

        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Modbus Master Tool"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.btnUpdate.setText(_translate("MainWindow", "Update"))

        self.btnWrite.setText(_translate("MainWindow", "Write To Register"))
        self.btnUnits.setText(_translate("MainWindow", "Save Units"))

        self.checkDebug.setText(_translate("MainWindow", "Debug"))
        self.label_2.setText(_translate("MainWindow", "Float Order [MSW LSW]"))
        self.comboBoxDataEncode.setItemText(0, _translate("MainWindow", "AB CD"))
        self.comboBoxDataEncode.setItemText(1, _translate("MainWindow", "CD AB"))
        self.label.setText(_translate("MainWindow", "Poll Period"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Units"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Write"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", ""))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Notes"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSetup.setText(_translate("MainWindow", "Setup"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))

        self.actionQuit.setText(_translate("MainWindow", "Quit"))

